### ISSUE TITLE
#include <barrier> error when build file 'demo18a01-barrier.cpp'

### ISSUE THREAD

**Issue by lfwin** [thanhit95/multi-threading#1]
Hi, when I build file 'demo18a01-barrier.cpp' with command 'g++ -o output_exe demo18a01-barrier.cpp -lpthread -std=c++17' in ubuntu 20.04, no such file errors occurs. Is this is because barrier  header file only included in c++20 from [this](https://en.cppreference.com/w/cpp/thread/barrier) ? how do I fix this error?

**Comment by thanhit95** [comment]
Hi,
You faced this error because std::barrier is supported since C++20 ([read here](https://en.cppreference.com/w/cpp/thread/barrier)).

Please try compiling by this command:
`g++ -o output_exe -lpthread -std=c++20 demo18a01-barrier.cpp`

(and make sure that g++/gcc in your computer supports C++20 standard)

Hope it works.

**Comment by lfwin** [comment]
Thanks.
